name: documentacion
on:
  push:
    branches:
      - main
jobs:
    compila:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: install donet
              uses: actions/setup-dotnet@v3.4.2
              with:
                  dotnet-version: '9.0.x'

            - name: install dependencies
              run:  dotnet restore
            - name: hello world by ricardo
              uses: ramtako8922/create-action@v1.0.3
              with:
                 who-to-greet: 'Diego'
            - name: build app
              run:  dotnet build --no-restore

              
    connvert_pdf:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
          
          
      
      
    
            
