name: documentacion
on:
  push:
    branches:
      - main
jobs:
    compila:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
    
            